---
-
  name: Download Wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- 
  name: Unpack Wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes
  become: yes

-
  name: Create Wordpress config page
  copy:
    src: '{{wp_installation_dir}}/wp-config-sample.php'
    dest: '{{wp_installation_dir}}/wp-config.php'
    remote_src: yes
  become: yes

-
  name: Set Wordpress config page
  replace:
    path: '{{wp_installation_dir}}/wp-config.php'
    regexp: '{{item.regex}}'
    replace: '{{item.replace}}'
  become: yes
  with_items:
    - { regex: database_name_here, replace: '{{wp_db_name}}' }
    - { regex: username_here, replace: '{{wp_db_user_name}}' }
    - { regex: password_here, replace: '{{wp_db_user_pass}}' }
    - { regex: localhost, replace: '{{wp_db_ip}}' }

-
  name: Copy Apache virtual host
  template:
    src: templates/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  become: yes
  notify:
    - restart apache