Vagrant.configure("2") do |config|   
    config.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
    end

    config.vm.define "wordpress" do |wordpress|
        wordpress.vm.network "private_network", ip: "172.17.177.50"
    end

    config.vm.define "mysql" do |mysql|
        mysql.vm.network "private_network", ip: "172.17.177.51"
    end
end