---
- 
  name: Update apt and install dependencies
  apt: 
    name:
      - mysql-server-5.7
      - python3-pymysql
    state: latest
    update_cache: yes
  become: yes

-
  name: Create MySQL database
  community.mysql.mysql_db:
    name: '{{wp_db_name}}'
    #login_user: root
    #login_password: 
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes

-
  name: Create MySQL user
  community.mysql.mysql_user:
    name: '{{wp_db_user_name}}'
    password: '{{wp_db_user_pass}}'
    priv: '{{wp_db_name}}.*:ALL'
    host: '%'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes

-
  name: Copy MySQL configs
  copy:
    src: files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  become: yes
  notify:
    - restart mysql